import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Api - JSON to Taringa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          API para convertir JSON a RSS para <a href="https://taringa.net" target="_blank" rel="noopener noreferrer">Taringa</a>
        </h1>

        <div className={styles.description}>
          <h3>
            Funciona muy simple, Usas la siguiente URL y al final coloca el usuario de taringa: 
          </h3>
          <p>
            Convierte el JSON que devuelve taringa con los ultimos 5 POST y lo convierte en RSS feed
          </p>
        </div>

        <div className={styles.code}>
          <p><b>Parametros disponibles:</b></p>
          <p>* user=NombreUsuario</p>
          <p>* count=Cantidad de post a mostrar - <b>Opcional</b>, Si no se agrega por defecto toma 5</p>
          <p><b>Ejemplo:</b></p>
          <a href="https://json-to-rss-taringa.vercel.app/api/rss?user=22matutex22&count=3" target="_blank" rel="noopener noreferrer">
            https://json-to-rss-taringa.vercel.app/api/rss?user=nombre_usuario&count=3
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.taringa.net/22matutex22" target="_blank" rel="noopener noreferrer">
          Created by 22matutex22
        </a>

        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
